services:
  #MySQL Config
  mysql-db:
    image: mysql:8.0
    container_name: mysql_pi_equivalencia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pi_eq
      MYSQL_DATABASE: pi_db
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
